lauguage: python

python:
  - 3.4
  - 3.5

before_install:
  - python --version
  - pip --version

install:
  - sudo pip install -r requirements.txt

script: 
  - if [[$TRAVIS_PYTHON_VERSION == 3.*]]; then python -m test.test; fi