lauguage: python

python:
  - 3.4
  - 3.5

before_install:
  - wget "https://bootstrap.pypa.io/get-pip.py" && sudo python3 get-pip.py
  - python3 --version
  - pip3 --version

install:
  - sudo pip3 install -r requirements.txt

script: 
  - python3 -m test.test