lauguage: python3

python:
  - 3.4
  - 3.5

before_install:
  # - wget "https://bootstrap.pypa.io/get-pip.py" && python3 get-pip.py
  - python --version
  - pip --version

install:
  - sudo pip install -r requirements.txt

script: 
  - python -m test.test