lauguage: python

python:
  - 3.4
  - 3.5

before_install:
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip

install:
  - sudo pip3 install -r requirements.txt

script: 
  - python3 -m test.test